# Generated by Django 5.0.6 on 2024-06-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_choice',
            field=models.CharField(choices=[('background1.jpg', 'Background 1'), ('background2.jpg', 'Background 2'), ('background2.jpg', 'Background 2')], default='background1.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='background_choice',
            field=models.CharField(choices=[('background1.jpg', 'Background 1'), ('background2.jpg', 'Background 2'), ('background2.jpg', 'Background 2')], max_length=100),
        ),
    ]
