# Generated by Django 5.0.6 on 2024-06-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_user_background_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_choice',
            field=models.CharField(choices=[('background1.jpg', 'Background 1'), ('background2.jpg', 'Background 2'), ('background2.jpg', 'Background 2')], default='backgrounddefault.jpg', max_length=100),
        ),
    ]
