# Generated by Django 5.0.6 on 2024-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_user_background_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_choice',
            field=models.CharField(choices=[('linear-gradient(to right, #bdc3c7, #2c3e50);', 'Grade Gray'), ('linear-gradient(to right, #2980b9, #6dd5fa, #ffffff)', 'Cool Sky'), ('linear-gradient(to right, #1f4037, #99f2c8);', 'Harvey'), ('linear-gradient(to right, #ffefba, #ffffff);', 'Margo'), ('linear-gradient(to right, #ef3b36, #ffffff);', 'Compare Now'), ('linear-gradient(to right, #12c2e9, #c471ed, #f64f59);', 'JShine'), ('linear-gradient(to right, #f0f2f0, #000c40);', 'What Lies Beyond')], default='linear-gradient(to right, #bdc3c7, #2c3e50);', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='background_choice',
            field=models.CharField(choices=[('linear-gradient(to right, #bdc3c7, #2c3e50);', 'Grade Gray'), ('linear-gradient(to right, #2980b9, #6dd5fa, #ffffff)', 'Cool Sky'), ('linear-gradient(to right, #1f4037, #99f2c8);', 'Harvey'), ('linear-gradient(to right, #ffefba, #ffffff);', 'Margo'), ('linear-gradient(to right, #ef3b36, #ffffff);', 'Compare Now'), ('linear-gradient(to right, #12c2e9, #c471ed, #f64f59);', 'JShine'), ('linear-gradient(to right, #f0f2f0, #000c40);', 'What Lies Beyond')], max_length=100),
        ),
    ]
